nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

# Suprimir warnings conhecidos do Material-UI v4 com React 18
# Material-UI v4 funciona perfeitamente com React 18, mas declara peer dependency antiga
logFilters:
  - code: YN0060
    text: '@material-ui/core'
    level: discard
  - code: YN0086
    level: discard
